/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PcoLicenceRouteImport } from './routes/pco-licence'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookConsultationRouteImport } from './routes/book-consultation'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicOneoffResetRouteImport } from './routes/api/public/oneoff-reset'
import { Route as AuthenticatedLearnModuleIdRouteImport } from './routes/_authenticated/learn.$moduleId'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin.quizzes'
import { Route as AuthenticatedAdminFollowUpRouteImport } from './routes/_authenticated/admin.follow-up'
import { Route as AuthenticatedAdminEnrollmentsRouteImport } from './routes/_authenticated/admin.enrollments'
import { Route as AuthenticatedAdminQuizzesModuleIdRouteImport } from './routes/_authenticated/admin.quizzes.$moduleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PcoLicenceRoute = PcoLicenceRouteImport.update({
  id: '/pco-licence',
  path: '/pco-licence',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConsultationRoute = BookConsultationRouteImport.update({
  id: '/book-consultation',
  path: '/book-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicOneoffResetRoute = ApiPublicOneoffResetRouteImport.update({
  id: '/api/public/oneoff-reset',
  path: '/api/public/oneoff-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLearnModuleIdRoute =
  AuthenticatedLearnModuleIdRouteImport.update({
    id: '/learn/$moduleId',
    path: '/learn/$moduleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/admin/reports',
    path: '/admin/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/admin/quizzes',
    path: '/admin/quizzes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFollowUpRoute =
  AuthenticatedAdminFollowUpRouteImport.update({
    id: '/admin/follow-up',
    path: '/admin/follow-up',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEnrollmentsRoute =
  AuthenticatedAdminEnrollmentsRouteImport.update({
    id: '/admin/enrollments',
    path: '/admin/enrollments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesModuleIdRoute =
  AuthenticatedAdminQuizzesModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/pco-licence': typeof PcoLicenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/follow-up': typeof AuthenticatedAdminFollowUpRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/learn/$moduleId': typeof AuthenticatedLearnModuleIdRoute
  '/api/public/oneoff-reset': typeof ApiPublicOneoffResetRoute
  '/admin/quizzes/$moduleId': typeof AuthenticatedAdminQuizzesModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/pco-licence': typeof PcoLicenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/admin/follow-up': typeof AuthenticatedAdminFollowUpRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/learn/$moduleId': typeof AuthenticatedLearnModuleIdRoute
  '/api/public/oneoff-reset': typeof ApiPublicOneoffResetRoute
  '/admin/quizzes/$moduleId': typeof AuthenticatedAdminQuizzesModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/book-consultation': typeof BookConsultationRoute
  '/contact': typeof ContactRoute
  '/pco-licence': typeof PcoLicenceRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/enrollments': typeof AuthenticatedAdminEnrollmentsRoute
  '/_authenticated/admin/follow-up': typeof AuthenticatedAdminFollowUpRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/learn/$moduleId': typeof AuthenticatedLearnModuleIdRoute
  '/api/public/oneoff-reset': typeof ApiPublicOneoffResetRoute
  '/_authenticated/admin/quizzes/$moduleId': typeof AuthenticatedAdminQuizzesModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/pco-licence'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/signup'
    | '/courses/$courseId'
    | '/courses/'
    | '/admin/enrollments'
    | '/admin/follow-up'
    | '/admin/quizzes'
    | '/admin/reports'
    | '/learn/$moduleId'
    | '/api/public/oneoff-reset'
    | '/admin/quizzes/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/pco-licence'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/signup'
    | '/courses/$courseId'
    | '/courses'
    | '/admin/enrollments'
    | '/admin/follow-up'
    | '/admin/quizzes'
    | '/admin/reports'
    | '/learn/$moduleId'
    | '/api/public/oneoff-reset'
    | '/admin/quizzes/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/book-consultation'
    | '/contact'
    | '/pco-licence'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/signup'
    | '/courses/$courseId'
    | '/courses/'
    | '/_authenticated/admin/enrollments'
    | '/_authenticated/admin/follow-up'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/reports'
    | '/_authenticated/learn/$moduleId'
    | '/api/public/oneoff-reset'
    | '/_authenticated/admin/quizzes/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  BookConsultationRoute: typeof BookConsultationRoute
  ContactRoute: typeof ContactRoute
  PcoLicenceRoute: typeof PcoLicenceRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiPublicOneoffResetRoute: typeof ApiPublicOneoffResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pco-licence': {
      id: '/pco-licence'
      path: '/pco-licence'
      fullPath: '/pco-licence'
      preLoaderRoute: typeof PcoLicenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-consultation': {
      id: '/book-consultation'
      path: '/book-consultation'
      fullPath: '/book-consultation'
      preLoaderRoute: typeof BookConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/oneoff-reset': {
      id: '/api/public/oneoff-reset'
      path: '/api/public/oneoff-reset'
      fullPath: '/api/public/oneoff-reset'
      preLoaderRoute: typeof ApiPublicOneoffResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learn/$moduleId': {
      id: '/_authenticated/learn/$moduleId'
      path: '/learn/$moduleId'
      fullPath: '/learn/$moduleId'
      preLoaderRoute: typeof AuthenticatedLearnModuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/follow-up': {
      id: '/_authenticated/admin/follow-up'
      path: '/admin/follow-up'
      fullPath: '/admin/follow-up'
      preLoaderRoute: typeof AuthenticatedAdminFollowUpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/enrollments': {
      id: '/_authenticated/admin/enrollments'
      path: '/admin/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AuthenticatedAdminEnrollmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/quizzes/$moduleId': {
      id: '/_authenticated/admin/quizzes/$moduleId'
      path: '/$moduleId'
      fullPath: '/admin/quizzes/$moduleId'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesModuleIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
  }
}

interface AuthenticatedAdminQuizzesRouteChildren {
  AuthenticatedAdminQuizzesModuleIdRoute: typeof AuthenticatedAdminQuizzesModuleIdRoute
}

const AuthenticatedAdminQuizzesRouteChildren: AuthenticatedAdminQuizzesRouteChildren =
  {
    AuthenticatedAdminQuizzesModuleIdRoute:
      AuthenticatedAdminQuizzesModuleIdRoute,
  }

const AuthenticatedAdminQuizzesRouteWithChildren =
  AuthenticatedAdminQuizzesRoute._addFileChildren(
    AuthenticatedAdminQuizzesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminEnrollmentsRoute: typeof AuthenticatedAdminEnrollmentsRoute
  AuthenticatedAdminFollowUpRoute: typeof AuthenticatedAdminFollowUpRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedLearnModuleIdRoute: typeof AuthenticatedLearnModuleIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminEnrollmentsRoute: AuthenticatedAdminEnrollmentsRoute,
  AuthenticatedAdminFollowUpRoute: AuthenticatedAdminFollowUpRoute,
  AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedLearnModuleIdRoute: AuthenticatedLearnModuleIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  BookConsultationRoute: BookConsultationRoute,
  ContactRoute: ContactRoute,
  PcoLicenceRoute: PcoLicenceRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiPublicOneoffResetRoute: ApiPublicOneoffResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
